ALTER TABLE EX1_024672.ADDRESS
 DROP PRIMARY KEY CASCADE;

DROP TABLE EX1_024672.ADDRESS CASCADE CONSTRAINTS;

CREATE TABLE EX1_024672.ADDRESS
(
  ADDRESS_ID        NUMBER,
  ZIPCODE           NUMBER,
  CITY_ID           NUMBER,
  ADDRESS_LINE1     VARCHAR2(1 BYTE),
  ADDRESS_LINE2     VARCHAR2(1 BYTE),
  ADDRESS_TYPE      VARCHAR2(1 BYTE),
  BILLING_ADDRESS1  VARCHAR2(1 BYTE),
  BILLING_ADDRESS2  VARCHAR2(1 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE EX1_024672.COUNTRY
 DROP PRIMARY KEY CASCADE;

DROP TABLE EX1_024672.COUNTRY CASCADE CONSTRAINTS;

CREATE TABLE EX1_024672.COUNTRY
(
  COUNTRY_ID           NUMBER,
  CULTURE              VARCHAR2(1 BYTE),
  CULTURE_DESCRIPTION  CHAR(3 CHAR)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE EX1_024672.CUSTOMERS
 DROP PRIMARY KEY CASCADE;

DROP TABLE EX1_024672.CUSTOMERS CASCADE CONSTRAINTS;

CREATE TABLE EX1_024672.CUSTOMERS
(
  CUSTOMER_ID       NUMBER,
  FIRST_NAME        VARCHAR2(1 BYTE),
  LAST_NAME         VARCHAR2(1 BYTE),
  COMPANY_NAME      VARCHAR2(1 BYTE),
  EMAIL_ADDRESS     VARCHAR2(1 BYTE),
  ADDRESS_TYPE      VARCHAR2(1 BYTE),
  ADDRESS_LINE1     VARCHAR2(1 BYTE),
  ADDRESS_LINE2     VARCHAR2(1 BYTE),
  BILLING_ADDRESS1  VARCHAR2(1 BYTE),
  BILLING_ADDRESS2  VARCHAR2(1 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE EX1_024672.ORDERS
 DROP PRIMARY KEY CASCADE;

DROP TABLE EX1_024672.ORDERS CASCADE CONSTRAINTS;

CREATE TABLE EX1_024672.ORDERS
(
  ORDER_ID     NUMBER,
  PRODUCT_ID   NUMBER,
  ORDER_QNTY   INTEGER,
  SHIP_METHOD  VARCHAR2(1 BYTE),
  CUSTOMER_ID  NUMBER
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE EX1_024672.PRODUCTS
 DROP PRIMARY KEY CASCADE;

DROP TABLE EX1_024672.PRODUCTS CASCADE CONSTRAINTS;

CREATE TABLE EX1_024672.PRODUCTS
(
  PRODUCT_ID        VARCHAR2(1 BYTE),
  PRODUCT_NAME      VARCHAR2(1 BYTE),
  PRODUCT_COLOR     VARCHAR2(1 BYTE),
  PRODUCT_WEIGHT    INTEGER,
  PRODUCT_CATEGORY  VARCHAR2(1 BYTE),
  LIST_PRICE        INTEGER,
  PRODUCT_SIZE      VARCHAR2(1 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE EX1_024672.STATES
 DROP PRIMARY KEY CASCADE;

DROP TABLE EX1_024672.STATES CASCADE CONSTRAINTS;

CREATE TABLE EX1_024672.STATES
(
  STATE_ID        NUMBER,
  STATE_PROVINCE  VARCHAR2(1 BYTE),
  COUNTRY_ID      NUMBER
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX EX1_024672.ADDRESS_PK ON EX1_024672.ADDRESS
(ADDRESS_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX EX1_024672.COUNTRY_PK ON EX1_024672.COUNTRY
(COUNTRY_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX EX1_024672.CUSTOMERS_PK ON EX1_024672.CUSTOMERS
(CUSTOMER_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX EX1_024672.ORDERS_PK ON EX1_024672.ORDERS
(ORDER_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX EX1_024672.PRODUCTS_PK ON EX1_024672.PRODUCTS
(PRODUCT_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX EX1_024672.STATES_PK ON EX1_024672.STATES
(STATE_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE EX1_024672.ADDRESS ADD (
  CONSTRAINT ADDRESS_PK
  PRIMARY KEY
  (ADDRESS_ID)
  USING INDEX EX1_024672.ADDRESS_PK
  ENABLE VALIDATE);

ALTER TABLE EX1_024672.COUNTRY ADD (
  CONSTRAINT COUNTRY_PK
  PRIMARY KEY
  (COUNTRY_ID)
  USING INDEX EX1_024672.COUNTRY_PK
  ENABLE VALIDATE);

ALTER TABLE EX1_024672.CUSTOMERS ADD (
  CONSTRAINT CUSTOMERS_PK
  PRIMARY KEY
  (CUSTOMER_ID)
  USING INDEX EX1_024672.CUSTOMERS_PK
  ENABLE VALIDATE);

ALTER TABLE EX1_024672.ORDERS ADD (
  CONSTRAINT ORDERS_PK
  PRIMARY KEY
  (ORDER_ID)
  USING INDEX EX1_024672.ORDERS_PK
  ENABLE VALIDATE);

ALTER TABLE EX1_024672.PRODUCTS ADD (
  CONSTRAINT PRODUCTS_PK
  PRIMARY KEY
  (PRODUCT_ID)
  USING INDEX EX1_024672.PRODUCTS_PK
  ENABLE VALIDATE);

ALTER TABLE EX1_024672.STATES ADD (
  CONSTRAINT STATES_PK
  PRIMARY KEY
  (STATE_ID)
  USING INDEX EX1_024672.STATES_PK
  ENABLE VALIDATE);
